engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/ClassLength:
        enabled: false
      Style/StringLiterals:
        enabled: false
      Metrics/LineLength:
        enabled: false
      Style/FrozenStringLiteralComment:
        enabled: false
      Documentation:
        enabled: false
      Rubocop/Lint/AssignmentInCondition:
        enabled: false
      Rubocop/Style/PercentLiteralDelimiters:
        enabled: false
  brakeman:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- config/**/*
- "**/vendor/**/*"
- "**/**/**/bootstrap.css"
- "**/**/**/bootstrap.js"
