AllCops:
  Rails:
    Enabled: true
  Excludes:
    - db/**
    - config/**/**
Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
