Card.create(original_text: 'the', translated_text: 'определенный артикль', review_date: '2017-05-24')
Card.create(original_text: 'and', translated_text: 'и; а, но', review_date: '2017-05-24')
Card.create(original_text: 'a', translated_text: 'неопределенный артикль', review_date: '2017-05-24')
Card.create(original_text: 'to', translated_text: 'к, в, на, до, для', review_date: '2017-05-24')
Card.create(original_text: 'was', translated_text: 'был, была, было;', review_date: '2017-05-24')
Card.create(original_text: 'I', translated_text: 'я', review_date: '2017-05-24')
Card.create(original_text: 'is', translated_text: '3- е л. ед. ч. наст. врем. гл. to be', review_date: '2017-05-24')
Card.create(original_text: 'of', translated_text: 'из, от, о, об', review_date: '2017-05-24')
Card.create(original_text: 'that', translated_text: 'тот, та, то', review_date: '2017-05-24')
Card.create(original_text: 'you', translated_text: 'ты, вы', review_date: '2017-05-24')
Card.create(original_text: 'he', translated_text: 'он', review_date: '2017-05-24')
Card.create(original_text: 'it', translated_text: 'он, она, оно; это', review_date: '2017-05-24')
Card.create(original_text: 'in', translated_text: 'в', review_date: '2017-05-24')
Card.create(original_text: 'his', translated_text: 'его', review_date: '2017-05-24')
Card.create(original_text: 'had', translated_text: 'имел, получал', review_date: '2017-05-24')
Card.create(original_text: 'do', translated_text: 'делать', review_date: '2017-05-24')
Card.create(original_text: 'with', translated_text: 'с, вместе с', review_date: '2017-05-24')
Card.create(original_text: 'not', translated_text: 'не, нет; ни', review_date: '2017-05-24')
Card.create(original_text: 'her', translated_text: 'её', review_date: '2017-05-24')
Card.create(original_text: 'for', translated_text: 'в течение, на, для', review_date: '2017-05-24')
Card.create(original_text: 'on', translated_text: 'на', review_date: '2017-05-24')
Card.create(original_text: 'at', translated_text: 'около, у; в, на', review_date: '2017-05-24')
Card.create(original_text: 'but', translated_text: 'только, лишь, кроме, но, а', review_date: '2017-05-24')
Card.create(original_text: 'she', translated_text: 'она', review_date: '2017-05-24')
Card.create(original_text: 'him', translated_text: 'его', review_date: '2017-05-24')
Card.create(original_text: 'as', translated_text: 'как, когда', review_date: '2017-05-24')
Card.create(original_text: 'are', translated_text: 'мн. ч. наст. врем. гл. to be', review_date: '2017-05-24')
Card.create(original_text: 'said', translated_text: 'говорил, сказал', review_date: '2017-05-24')
Card.create(original_text: 'they', translated_text: 'они', review_date: '2017-05-24')
Card.create(original_text: 'we', translated_text: 'мы', review_date: '2017-05-24')
Card.create(original_text: 'all', translated_text: 'все, вся, всё', review_date: '2017-05-24')
Card.create(original_text: 'this', translated_text: 'этот, эта, это', review_date: '2017-05-24')
Card.create(original_text: 'have', translated_text: 'иметь; получать; быть должным', review_date: '2017-05-24')
Card.create(original_text: 'there', translated_text: 'там, туда, здесь', review_date: '2017-05-24')
Card.create(original_text: 'what', translated_text: 'что', review_date: '2017-05-24')
Card.create(original_text: 'out', translated_text: 'вне, снаружи; за', review_date: '2017-05-24')
Card.create(original_text: 'up', translated_text: 'наверх(у), выше; вверх по, вдоль по', review_date: '2017-05-24')
Card.create(original_text: 'one', translated_text: 'один', review_date: '2017-05-24')
Card.create(original_text: 'from', translated_text: 'от, из, с', review_date: '2017-05-24')
Card.create(original_text: 'me', translated_text: 'мне, меня', review_date: '2017-05-24')
Card.create(original_text: 'go', translated_text: 'идти, ехать ; уходить', review_date: '2017-05-24')
Card.create(original_text: 'were', translated_text: 'были', review_date: '2017-05-24')
Card.create(original_text: 'would', translated_text: '1) вспом. глагол.; 2) модальный глагол', review_date: '2017-05-24')
Card.create(original_text: 'like', translated_text: 'похожий; как, подобно; любить, нравиться', review_date: '2017-05-24')
Card.create(original_text: 'when', translated_text: 'когда', review_date: '2017-05-24')
Card.create(original_text: 'could', translated_text: 'мог, умел', review_date: '2017-05-24')
Card.create(original_text: 'then', translated_text: 'тогда; затем', review_date: '2017-05-24')
Card.create(original_text: 'be', translated_text: 'быть, существовать; находиться', review_date: '2017-05-24')
Card.create(original_text: 'them', translated_text: 'их , им', review_date: '2017-05-24')
Card.create(original_text: 'did', translated_text: 'делал, выполнял', review_date: '2017-05-24')
Card.create(original_text: 'been', translated_text: 'был, была, было', review_date: '2017-05-24')
Card.create(original_text: 'now', translated_text: 'теперь, сейчас', review_date: '2017-05-24')
Card.create(original_text: 'look', translated_text: 'взгляд, смотреть', review_date: '2017-05-24')
Card.create(original_text: 'back', translated_text: 'спина, задний', review_date: '2017-05-24')
Card.create(original_text: 'my', translated_text: 'мой', review_date: '2017-05-24')
Card.create(original_text: 'no', translated_text: 'нет, не', review_date: '2017-05-24')
Card.create(original_text: 'your', translated_text: 'твой, ваш', review_date: '2017-05-24')
Card.create(original_text: 'which', translated_text: 'который; что', review_date: '2017-05-24')
Card.create(original_text: 'about', translated_text: 'кругом, вокруг; около; о, об, относительно', review_date: '2017-05-24')
Card.create(original_text: 'time', translated_text: 'время; раз', review_date: '2017-05-24')
Card.create(original_text: 'down', translated_text: 'вниз, внизу; вниз по, вдоль по', review_date: '2017-05-24')
Card.create(original_text: 'into', translated_text: 'в', review_date: '2017-05-24')
Card.create(original_text: 'who', translated_text: 'кто; который', review_date: '2017-05-24')
Card.create(original_text: 'can', translated_text: 'мочь; уметь', review_date: '2017-05-24')
Card.create(original_text: 'know', translated_text: 'знать', review_date: '2017-05-24')
Card.create(original_text: 'if', translated_text: 'если', review_date: '2017-05-24')
Card.create(original_text: 'just', translated_text: 'только что', review_date: '2017-05-24')
Card.create(original_text: 'their', translated_text: 'их', review_date: '2017-05-24')
Card.create(original_text: 'get', translated_text: 'получать; брать; приобретать', review_date: '2017-05-24')
Card.create(original_text: 'over', translated_text: 'над; свыше', review_date: '2017-05-24')
Card.create(original_text: 'more', translated_text: 'больше, более', review_date: '2017-05-24')
Card.create(original_text: 'some', translated_text: 'несколько', review_date: '2017-05-24')
Card.create(original_text: 'man', translated_text: 'человек, мужчина', review_date: '2017-05-24')
Card.create(original_text: 'come', translated_text: 'приходить, приезжать; случаться', review_date: '2017-05-24')
Card.create(original_text: 'an', translated_text: 'неопределённый артикль', review_date: '2017-05-24')
Card.create(original_text: 'so', translated_text: 'так; тоже, также', review_date: '2017-05-24')
Card.create(original_text: 'other', translated_text: 'другой, иной, еще', review_date: '2017-05-24')
Card.create(original_text: 'little', translated_text: 'маленький', review_date: '2017-05-24')
Card.create(original_text: 'see', translated_text: 'видеть', review_date: '2017-05-24')
Card.create(original_text: 'here', translated_text: 'здесь, тут', review_date: '2017-05-24')
Card.create(original_text: 'thing', translated_text: 'вещь, предмет', review_date: '2017-05-24')
Card.create(original_text: 'hand', translated_text: 'рука', review_date: '2017-05-24')
Card.create(original_text: 'by', translated_text: 'у , около', review_date: '2017-05-24')
Card.create(original_text: 'will', translated_text: '1) вспом. гл. будущ. врем.; 2) модальный глагол', review_date: '2017-05-24')
Card.create(original_text: 'way', translated_text: 'путь, дорога', review_date: '2017-05-24')
Card.create(original_text: 'again', translated_text: 'опять, снова', review_date: '2017-05-24')
Card.create(original_text: 'right', translated_text: 'правый; верно', review_date: '2017-05-24')
Card.create(original_text: 'only', translated_text: 'только', review_date: '2017-05-24')
Card.create(original_text: 'am', translated_text: '1-е л. ед.ч. наст. врем. гл. to be', review_date: '2017-05-24')
Card.create(original_text: 'how', translated_text: 'как', review_date: '2017-05-24')
Card.create(original_text: 'think', translated_text: 'думать; считать, полагать', review_date: '2017-05-24')
Card.create(original_text: 'or', translated_text: 'или', review_date: '2017-05-24')
Card.create(original_text: 'got', translated_text: 'получил', review_date: '2017-05-24')
Card.create(original_text: 'good', translated_text: 'хороший; добро', review_date: '2017-05-24')
Card.create(original_text: 'eye', translated_text: 'глаз; взгляд', review_date: '2017-05-24')
Card.create(original_text: 'well', translated_text: 'хорошо', review_date: '2017-05-24')
Card.create(original_text: 'thought', translated_text: 'думал, мысль', review_date: '2017-05-24')
Card.create(original_text: 'day', translated_text: 'день; сутки', review_date: '2017-05-24')
Card.create(original_text: 'two', translated_text: 'два', review_date: '2017-05-24')
Card.create(original_text: 'than', translated_text: 'чем, нежели', review_date: '2017-05-24')
Card.create(original_text: 'before', translated_text: 'перед; раньше', review_date: '2017-05-24')
Card.create(original_text: 'where', translated_text: 'где; куда', review_date: '2017-05-24')
Card.create(original_text: 'very', translated_text: 'очень', review_date: '2017-05-24')
Card.create(original_text: 'say', translated_text: 'говорить, сказать', review_date: '2017-05-24')
Card.create(original_text: 'came', translated_text: 'приходил, приезжал', review_date: '2017-05-24')
Card.create(original_text: 'any', translated_text: 'какой-нибудь', review_date: '2017-05-24')
Card.create(original_text: 'old', translated_text: 'старый', review_date: '2017-05-24')
Card.create(original_text: 'still', translated_text: 'тихий; все еще', review_date: '2017-05-24')
Card.create(original_text: 'after', translated_text: 'после, через; потом', review_date: '2017-05-24')
Card.create(original_text: 'off', translated_text: 'с , от', review_date: '2017-05-24')
Card.create(original_text: 'has', translated_text: 'имел, имела', review_date: '2017-05-24')
Card.create(original_text: 'never', translated_text: 'никогда', review_date: '2017-05-24')
Card.create(original_text: 'going', translated_text: 'живущий, существующий, ходьба', review_date: '2017-05-24')
Card.create(original_text: 'even', translated_text: 'даже; ровно', review_date: '2017-05-24')
Card.create(original_text: 'much', translated_text: 'много', review_date: '2017-05-24')
Card.create(original_text: 'went', translated_text: 'шёл, ехал', review_date: '2017-05-24')
Card.create(original_text: 'too', translated_text: 'также; слишком', review_date: '2017-05-24')
Card.create(original_text: 'away', translated_text: 'далеко; прочь', review_date: '2017-05-24')
Card.create(original_text: 'something', translated_text: 'что-то, что-нибудь; примерно', review_date: '2017-05-24')
Card.create(original_text: 'first', translated_text: 'первый; сначала', review_date: '2017-05-24')
Card.create(original_text: 'make', translated_text: 'делать, производить; совершать', review_date: '2017-05-24')
Card.create(original_text: 'head', translated_text: 'голова', review_date: '2017-05-24')
Card.create(original_text: 'want', translated_text: 'хотеть', review_date: '2017-05-24')
Card.create(original_text: 'turn', translated_text: 'поворачивать(ся)', review_date: '2017-05-24')
Card.create(original_text: 'face', translated_text: 'лицо', review_date: '2017-05-24')
Card.create(original_text: 'made', translated_text: 'сделан, сделанный', review_date: '2017-05-24')
Card.create(original_text: 'seem', translated_text: 'казаться', review_date: '2017-05-24')
Card.create(original_text: 'call', translated_text: 'призыв; звать', review_date: '2017-05-24')
Card.create(original_text: 'ask', translated_text: 'спрашивать', review_date: '2017-05-24')
Card.create(original_text: 'should', translated_text: '1) вспом. глагол; 2)  должен, следует', review_date: '2017-05-24')
Card.create(original_text: 'through', translated_text: 'через , сквозь', review_date: '2017-05-24')
Card.create(original_text: 'long', translated_text: 'длинный; долго', review_date: '2017-05-24')
Card.create(original_text: 'let', translated_text: 'позволять', review_date: '2017-05-24')
Card.create(original_text: 'take', translated_text: 'брать; доставлять; принимать', review_date: '2017-05-24')
Card.create(original_text: 'saw', translated_text: 'видел, пила', review_date: '2017-05-24')
Card.create(original_text: 'around', translated_text: 'кругом, вокруг; поблизости', review_date: '2017-05-24')
Card.create(original_text: 'our', translated_text: 'наш', review_date: '2017-05-24')
Card.create(original_text: 'door', translated_text: 'дверь', review_date: '2017-05-24')
Card.create(original_text: 'last', translated_text: 'последний', review_date: '2017-05-24')
Card.create(original_text: 'tell', translated_text: 'говорить', review_date: '2017-05-24')
Card.create(original_text: 'might', translated_text: 'мог, мог бы, энергия', review_date: '2017-05-24')
Card.create(original_text: 'own', translated_text: 'свой; владеть', review_date: '2017-05-24')
Card.create(original_text: 'night', translated_text: 'ночь; вечер', review_date: '2017-05-24')
Card.create(original_text: 'year', translated_text: 'год', review_date: '2017-05-24')
Card.create(original_text: 'must', translated_text: 'должен, обязан', review_date: '2017-05-24')
Card.create(original_text: 'because', translated_text: 'потому что', review_date: '2017-05-24')
Card.create(original_text: 'voice', translated_text: 'голос', review_date: '2017-05-24')
Card.create(original_text: 'such', translated_text: 'такой, тот, подобный', review_date: '2017-05-24')
Card.create(original_text: 'room', translated_text: 'комната', review_date: '2017-05-24')
Card.create(original_text: 'place', translated_text: 'место; помещать', review_date: '2017-05-24')
Card.create(original_text: 'those', translated_text: 'те', review_date: '2017-05-24')
Card.create(original_text: 'work', translated_text: 'работа; работать', review_date: '2017-05-24')
Card.create(original_text: 'put', translated_text: 'положить', review_date: '2017-05-24')
Card.create(original_text: 'bill', translated_text: 'счёт, законопроект, клюв', review_date: '2017-05-24')
Card.create(original_text: 'nothing', translated_text: 'ничего', review_date: '2017-05-24')
Card.create(original_text: 'most', translated_text: 'самый большой, наибольший', review_date: '2017-05-24')
Card.create(original_text: 'house', translated_text: 'дом', review_date: '2017-05-24')
Card.create(original_text: 'why', translated_text: 'почему', review_date: '2017-05-24')
Card.create(original_text: 'may', translated_text: 'мочь; май', review_date: '2017-05-24')
Card.create(original_text: 'side', translated_text: 'сторона', review_date: '2017-05-24')
Card.create(original_text: 'great', translated_text: 'большой, великий', review_date: '2017-05-24')
Card.create(original_text: 'these', translated_text: 'эти', review_date: '2017-05-24')
Card.create(original_text: 'white', translated_text: 'белый', review_date: '2017-05-24')
Card.create(original_text: 'people', translated_text: 'люди, нация, народ', review_date: '2017-05-24')
Card.create(original_text: 'upon', translated_text: 'на', review_date: '2017-05-24')
Card.create(original_text: 'left', translated_text: 'левый, налево, покинул, уехал', review_date: '2017-05-24')
Card.create(original_text: 'open', translated_text: 'открывать(ся)', review_date: '2017-05-24')
Card.create(original_text: 'himself', translated_text: 'себя; сам', review_date: '2017-05-24')
Card.create(original_text: 'friend', translated_text: 'друг', review_date: '2017-05-24')
Card.create(original_text: 'felt', translated_text: 'чувствовал, войлок', review_date: '2017-05-24')
Card.create(original_text: 'three', translated_text: 'три', review_date: '2017-05-24')
Card.create(original_text: 'knew', translated_text: 'знал', review_date: '2017-05-24')
Card.create(original_text: 'another', translated_text: 'другой', review_date: '2017-05-24')
Card.create(original_text: 'once', translated_text: 'один раз, однажды, когда-то', review_date: '2017-05-24')
Card.create(original_text: 'give', translated_text: 'давать', review_date: '2017-05-24')
Card.create(original_text: 'almost', translated_text: 'почти', review_date: '2017-05-24')
Card.create(original_text: 'mind', translated_text: 'разум; мнение', review_date: '2017-05-24')
Card.create(original_text: 'took', translated_text: 'брал, хватал', review_date: '2017-05-24')
Card.create(original_text: 'light', translated_text: 'свет; освещать(ся)', review_date: '2017-05-24')
Card.create(original_text: 'yes', translated_text: 'да', review_date: '2017-05-24')
Card.create(original_text: 'love', translated_text: 'любовь, любить', review_date: '2017-05-24')
Card.create(original_text: 'end', translated_text: 'конец; кончать(ся)', review_date: '2017-05-24')
Card.create(original_text: 'boy', translated_text: 'мальчик, парень', review_date: '2017-05-24')
Card.create(original_text: 'looking', translated_text: 'смотреть', review_date: '2017-05-24')
Card.create(original_text: 'while', translated_text: 'в то время как', review_date: '2017-05-24')
Card.create(original_text: 'sound', translated_text: 'звук; звучать', review_date: '2017-05-24')
Card.create(original_text: 'moment', translated_text: 'миг, момент', review_date: '2017-05-24')
Card.create(original_text: 'men', translated_text: 'люди, мужчины', review_date: '2017-05-24')
Card.create(original_text: 'ever', translated_text: 'когда-либо', review_date: '2017-05-24')
Card.create(original_text: 'under', translated_text: 'под; ниже', review_date: '2017-05-24')
Card.create(original_text: 'told', translated_text: 'говорил, рассказывал', review_date: '2017-05-24')
Card.create(original_text: 'really', translated_text: 'действительно', review_date: '2017-05-24')
Card.create(original_text: 'life', translated_text: 'жизнь', review_date: '2017-05-24')
Card.create(original_text: 'world', translated_text: 'мир, свет; вселенная', review_date: '2017-05-24')
Card.create(original_text: 'same', translated_text: 'тот же самый', review_date: '2017-05-24')
Card.create(original_text: 'sure', translated_text: 'уверенный; конечно', review_date: '2017-05-24')
Card.create(original_text: 'new', translated_text: 'новый', review_date: '2017-05-24')
Card.create(original_text: 'found', translated_text: 'находил, встречал', review_date: '2017-05-24')
Card.create(original_text: 'being', translated_text: 'жизнь, существование', review_date: '2017-05-24')
Card.create(original_text: 'enough', translated_text: 'достаточно', review_date: '2017-05-24')
Card.create(original_text: 'gone', translated_text: 'ушли, ушёл, ушедший', review_date: '2017-05-24')
Card.create(original_text: 'many', translated_text: 'много, многие', review_date: '2017-05-24')
Card.create(original_text: 'big', translated_text: 'большой', review_date: '2017-05-24')
Card.create(original_text: 'does', translated_text: '3-е л. ед. наст. времени от do', review_date: '2017-05-24')
Card.create(original_text: 'every', translated_text: 'каждый, всякий', review_date: '2017-05-24')
Card.create(original_text: 'began', translated_text: 'начинал, начиналось', review_date: '2017-05-24')
Card.create(original_text: 'always', translated_text: 'всегда', review_date: '2017-05-24')
Card.create(original_text: 'girl', translated_text: 'девочка, девушка', review_date: '2017-05-24')
Card.create(original_text: 'home', translated_text: 'дом', review_date: '2017-05-24')
Card.create(original_text: 'without', translated_text: 'без, в отсутствие', review_date: '2017-05-24')
Card.create(original_text: 'heard', translated_text: 'слышал, услышал', review_date: '2017-05-24')
Card.create(original_text: 'toward(s)', translated_text: 'к', review_date: '2017-05-24')
Card.create(original_text: 'need', translated_text: 'нуждаться', review_date: '2017-05-24')
Card.create(original_text: 'stop', translated_text: 'остановка; останавливать(ся)', review_date: '2017-05-24')
Card.create(original_text: 'maybe', translated_text: 'может быть', review_date: '2017-05-24')
Card.create(original_text: 'part', translated_text: 'доля, часть, отчасти', review_date: '2017-05-24')
Card.create(original_text: 'use', translated_text: 'применение, польза; употреблять', review_date: '2017-05-24')
Card.create(original_text: 'okay или OK', translated_text: 'хорошо!, ладно!, есть!', review_date: '2017-05-24')
Card.create(original_text: 'use', translated_text: 'использовать, применять', review_date: '2017-05-24')
Card.create(original_text: 'though', translated_text: 'хотя, даже, тем не менее', review_date: '2017-05-24')
Card.create(original_text: 'far', translated_text: 'дальний; далеко', review_date: '2017-05-24')
Card.create(original_text: 'name', translated_text: 'имя; название', review_date: '2017-05-24')
Card.create(original_text: 'word', translated_text: 'слово', review_date: '2017-05-24')
Card.create(original_text: 'behind', translated_text: 'за; сзади , позади', review_date: '2017-05-24')
Card.create(original_text: 'try', translated_text: 'пытаться, пробовать', review_date: '2017-05-24')
Card.create(original_text: 'help', translated_text: 'помощь; помогать', review_date: '2017-05-24')
Card.create(original_text: 'also', translated_text: 'тоже, также', review_date: '2017-05-24')
Card.create(original_text: 'better', translated_text: 'лучший, наилучший', review_date: '2017-05-24')
Card.create(original_text: 'mean', translated_text: 'середина; значить; подразумевать', review_date: '2017-05-24')
Card.create(original_text: 'father', translated_text: 'отец', review_date: '2017-05-24')
Card.create(original_text: 'against', translated_text: 'против', review_date: '2017-05-24')
Card.create(original_text: 'anything', translated_text: 'что-нибудь; что угодно', review_date: '2017-05-24')
Card.create(original_text: 'start', translated_text: 'начало; начинать(ся)', review_date: '2017-05-24')
Card.create(original_text: 'yet', translated_text: 'ещё, всё ещё', review_date: '2017-05-24')
Card.create(original_text: 'walk', translated_text: 'ходьба; ходить', review_date: '2017-05-24')
Card.create(original_text: 'woman', translated_text: 'женщина', review_date: '2017-05-24')
Card.create(original_text: 'seen', translated_text: 'видел', review_date: '2017-05-24')
Card.create(original_text: 'close', translated_text: 'близкий, тесный; близко; закрывать(ся)', review_date: '2017-05-24')
Card.create(original_text: 'remember', translated_text: 'помнить, вспоминать', review_date: '2017-05-24')
Card.create(original_text: 'car', translated_text: 'автомобиль, машина', review_date: '2017-05-24')
Card.create(original_text: 'between', translated_text: 'между', review_date: '2017-05-24')
Card.create(original_text: 'until', translated_text: 'до, (до тех пор) пока (не)', review_date: '2017-05-24')
Card.create(original_text: 'both', translated_text: 'оба', review_date: '2017-05-24')
Card.create(original_text: 'done', translated_text: 'сделанный; выполненный', review_date: '2017-05-24')
Card.create(original_text: 'god', translated_text: 'бог', review_date: '2017-05-24')
Card.create(original_text: 'find', translated_text: 'находить, обнаруживать', review_date: '2017-05-24')
Card.create(original_text: 'water', translated_text: 'вода', review_date: '2017-05-24')
Card.create(original_text: 'arm', translated_text: 'рука;', review_date: '2017-05-24')
Card.create(original_text: 'few', translated_text: 'немного; a ~ несколько', review_date: '2017-05-24')
Card.create(original_text: 'hear', translated_text: 'слышать; слушать', review_date: '2017-05-24')
Card.create(original_text: 'dog', translated_text: 'собака', review_date: '2017-05-24')
Card.create(original_text: 'happen', translated_text: 'случаться', review_date: '2017-05-24')
Card.create(original_text: 'its', translated_text: 'его, её (о предмете)', review_date: '2017-05-24')
Card.create(original_text: 'book', translated_text: 'книга', review_date: '2017-05-24')
Card.create(original_text: 'morning', translated_text: 'утро, утренний', review_date: '2017-05-24')
Card.create(original_text: 'kid', translated_text: 'ребёнок, малыш', review_date: '2017-05-24')
Card.create(original_text: 'street', translated_text: 'улица', review_date: '2017-05-24')
Card.create(original_text: 'believe', translated_text: 'верить', review_date: '2017-05-24')
Card.create(original_text: 'talk', translated_text: 'разговор; говорить', review_date: '2017-05-24')
Card.create(original_text: 'mother', translated_text: 'мать', review_date: '2017-05-24')
Card.create(original_text: 'kind', translated_text: 'сорт, разряд; вид, класс', review_date: '2017-05-24')
Card.create(original_text: 'coming', translated_text: 'прибытие, приезд,', review_date: '2017-05-24')
Card.create(original_text: 'each', translated_text: 'каждый, всякий', review_date: '2017-05-24')
Card.create(original_text: 'black', translated_text: 'черный', review_date: '2017-05-24')
Card.create(original_text: 'half', translated_text: 'половина', review_date: '2017-05-24')
Card.create(original_text: 'red', translated_text: 'красный, алый, рыжий', review_date: '2017-05-24')
Card.create(original_text: 'stood', translated_text: 'стоял, водружал', review_date: '2017-05-24')
Card.create(original_text: 'young', translated_text: 'молодой, юный', review_date: '2017-05-24')
Card.create(original_text: 'shall', translated_text: 'вспомогательный и модальный глагол', review_date: '2017-05-24')
Card.create(original_text: 'show', translated_text: 'показ;  показывать', review_date: '2017-05-24')
Card.create(original_text: 'feet', translated_text: 'ноги', review_date: '2017-05-24')
Card.create(original_text: 'feel', translated_text: 'чувствовать', review_date: '2017-05-24')
Card.create(original_text: 'keep', translated_text: 'держать', review_date: '2017-05-24')
Card.create(original_text: 'next', translated_text: 'следующий; будущий; потом', review_date: '2017-05-24')
Card.create(original_text: 'dark', translated_text: 'тёмный', review_date: '2017-05-24')
Card.create(original_text: 'along', translated_text: 'вдоль, по, рядом', review_date: '2017-05-24')
Card.create(original_text: 'pass', translated_text: 'проход, путь, передавать', review_date: '2017-05-24')
Card.create(original_text: 'course', translated_text: 'курс, ход, течение', review_date: '2017-05-24')
Card.create(original_text: 'window', translated_text: 'окно', review_date: '2017-05-24')
Card.create(original_text: 'dead', translated_text: 'мертвый', review_date: '2017-05-24')
Card.create(original_text: 'hour', translated_text: 'час, время', review_date: '2017-05-24')
Card.create(original_text: 'wanted', translated_text: 'разыскиваемый полицией', review_date: '2017-05-24')
Card.create(original_text: 'matter', translated_text: 'вещество, материал, иметь значение', review_date: '2017-05-24')
Card.create(original_text: 'since', translated_text: 'с тех пор, с, после', review_date: '2017-05-24')
Card.create(original_text: 'cry', translated_text: 'плакать', review_date: '2017-05-24')
Card.create(original_text: 'heart', translated_text: 'сердце', review_date: '2017-05-24')
Card.create(original_text: 'answer', translated_text: 'ответ, отвечать; откликаться', review_date: '2017-05-24')
Card.create(original_text: 'small', translated_text: 'маленький', review_date: '2017-05-24')
Card.create(original_text: 'yeah', translated_text: 'да', review_date: '2017-05-24')
Card.create(original_text: 'doing', translated_text: 'дела, акт, действие', review_date: '2017-05-24')
Card.create(original_text: 'four', translated_text: 'четыре', review_date: '2017-05-24')
Card.create(original_text: 'move', translated_text: 'двигать(ся)', review_date: '2017-05-24')
Card.create(original_text: 'live', translated_text: 'жить, существовать,', review_date: '2017-05-24')
Card.create(original_text: 'suddenly', translated_text: 'вдруг', review_date: '2017-05-24')
Card.create(original_text: 'five', translated_text: 'пять', review_date: '2017-05-24')
Card.create(original_text: 'body', translated_text: 'тело', review_date: '2017-05-24')
Card.create(original_text: 'fire', translated_text: 'огонь; пожар; стрелять; поджигать', review_date: '2017-05-24')
Card.create(original_text: 'mouth', translated_text: 'рот', review_date: '2017-05-24')
Card.create(original_text: 'leave', translated_text: 'покидать', review_date: '2017-05-24')
Card.create(original_text: 'smile', translated_text: 'улыбка; улыбаться', review_date: '2017-05-24')
Card.create(original_text: 'state', translated_text: 'государство, страна, штат', review_date: '2017-05-24')
Card.create(original_text: 'family', translated_text: 'семья', review_date: '2017-05-24')
Card.create(original_text: 'road', translated_text: 'дорога, путь', review_date: '2017-05-24')
Card.create(original_text: 'front', translated_text: 'передний', review_date: '2017-05-24')
Card.create(original_text: 'laugh', translated_text: 'смех, смеяться', review_date: '2017-05-24')
Card.create(original_text: 'gave', translated_text: 'давал, передавал', review_date: '2017-05-24')
Card.create(original_text: 'across', translated_text: 'через, сквозь; поперек', review_date: '2017-05-24')
Card.create(original_text: 'step', translated_text: 'шаг; шагать', review_date: '2017-05-24')
Card.create(original_text: 'quite', translated_text: 'вполне, совершенно; полностью', review_date: '2017-05-24')
Card.create(original_text: 'change', translated_text: 'менять, изменять', review_date: '2017-05-24')
Card.create(original_text: 'later', translated_text: 'позже, более поздний', review_date: '2017-05-24')
Card.create(original_text: 'together', translated_text: 'вместе; совместно', review_date: '2017-05-24')
Card.create(original_text: 'soon', translated_text: 'скоро, вскоре', review_date: '2017-05-24')
Card.create(original_text: 'least', translated_text: 'минимальный, наименьший', review_date: '2017-05-24')
Card.create(original_text: 'second', translated_text: 'секунда; второй', review_date: '2017-05-24')
Card.create(original_text: 'kill', translated_text: 'убивать', review_date: '2017-05-24')
Card.create(original_text: 'watch', translated_text: '1) смотреть, следить; наблюдение; 2) часы', review_date: '2017-05-24')
Card.create(original_text: 'wife', translated_text: 'жена, супруга', review_date: '2017-05-24')
Card.create(original_text: 'hard', translated_text: 'жёсткий, твёрдый', review_date: '2017-05-24')
Card.create(original_text: 'wait', translated_text: 'ждать', review_date: '2017-05-24')
Card.create(original_text: 'sat', translated_text: 'сидел, находился', review_date: '2017-05-24')
Card.create(original_text: 'feeling', translated_text: 'ощущение, чувство', review_date: '2017-05-24')
Card.create(original_text: 'high', translated_text: 'высокий', review_date: '2017-05-24')
Card.create(original_text: 'guy', translated_text: 'парень', review_date: '2017-05-24')
Card.create(original_text: 'idea', translated_text: 'идея; мысль', review_date: '2017-05-24')
Card.create(original_text: 'line', translated_text: 'линия; черта, строка', review_date: '2017-05-24')
Card.create(original_text: 'fear', translated_text: 'боязнь, страх', review_date: '2017-05-24')
Card.create(original_text: 'miss', translated_text: 'потеря, утрата', review_date: '2017-05-24')
Card.create(original_text: 'bad', translated_text: 'плохой', review_date: '2017-05-24')
Card.create(original_text: 'hair', translated_text: 'волосы', review_date: '2017-05-24')
Card.create(original_text: 'minute', translated_text: 'минута', review_date: '2017-05-24')
Card.create(original_text: 'everything', translated_text: 'всё', review_date: '2017-05-24')
Card.create(original_text: 'please', translated_text: 'пожалуйста, желать, хотеть', review_date: '2017-05-24')
Card.create(original_text: 'please', translated_text: 'пожалуйста, желать, хотеть', review_date: '2017-05-24')
Card.create(original_text: 'gray', translated_text: 'серый, седой', review_date: '2017-05-24')
Card.create(original_text: 'follow', translated_text: 'следовать (за)', review_date: '2017-05-24')
Card.create(original_text: 'hope', translated_text: 'надежда, надеяться', review_date: '2017-05-24')
Card.create(original_text: 'blood', translated_text: 'кровь', review_date: '2017-05-24')
Card.create(original_text: 'won', translated_text: 'выиграл, победил', review_date: '2017-05-24')
Card.create(original_text: 'air', translated_text: 'воздух; атмосфера', review_date: '2017-05-24')
Card.create(original_text: 'perhaps', translated_text: 'может быть, возможно', review_date: '2017-05-24')
Card.create(original_text: 'set', translated_text: 'ставить, класть', review_date: '2017-05-24')
Card.create(original_text: 'tree', translated_text: 'дерево, древо', review_date: '2017-05-24')
Card.create(original_text: 'run', translated_text: 'бежать', review_date: '2017-05-24')
Card.create(original_text: 'death', translated_text: 'смерть', review_date: '2017-05-24')
Card.create(original_text: 'else', translated_text: 'ещё, кроме', review_date: '2017-05-24')
Card.create(original_text: 'already', translated_text: 'уже', review_date: '2017-05-24')
Card.create(original_text: 'myself', translated_text: 'себя, себе, собой', review_date: '2017-05-24')
Card.create(original_text: 'bed', translated_text: 'кровать', review_date: '2017-05-24')
Card.create(original_text: 'lot', translated_text: 'жребий, доля. лот', review_date: '2017-05-24')
Card.create(original_text: 'point', translated_text: 'острие; точка; пункт; смысл', review_date: '2017-05-24')
Card.create(original_text: 'money', translated_text: 'деньги', review_date: '2017-05-24')
Card.create(original_text: 'getting', translated_text: 'получить, приобрести', review_date: '2017-05-24')
Card.create(original_text: 'rest', translated_text: 'отдых, отдыхать', review_date: '2017-05-24')
Card.create(original_text: 'whole', translated_text: 'весь, целый; полный', review_date: '2017-05-24')
Card.create(original_text: 'pull', translated_text: 'тянуть, тащить', review_date: '2017-05-24')
Card.create(original_text: 'business', translated_text: 'дело, занятие; бизнес', review_date: '2017-05-24')
Card.create(original_text: 'either', translated_text: 'один из двух; тот или другой, или', review_date: '2017-05-24')
Card.create(original_text: 'lady', translated_text: 'леди, дама', review_date: '2017-05-24')
Card.create(original_text: 'play', translated_text: 'играть, игра', review_date: '2017-05-24')
Card.create(original_text: 'suppose', translated_text: 'полагать, думать', review_date: '2017-05-24')
Card.create(original_text: 'top', translated_text: 'верхушка, верхний, топ', review_date: '2017-05-24')
Card.create(original_text: 'reach', translated_text: 'достигать', review_date: '2017-05-24')
Card.create(original_text: 'week', translated_text: 'неделя', review_date: '2017-05-24')
Card.create(original_text: 'thank', translated_text: 'благодарить', review_date: '2017-05-24')
Card.create(original_text: 'wall', translated_text: 'стена', review_date: '2017-05-24')
Card.create(original_text: 'real', translated_text: 'реальный', review_date: '2017-05-24')
Card.create(original_text: 'held', translated_text: 'держал, обнимал', review_date: '2017-05-24')
Card.create(original_text: 'best', translated_text: 'самый лучший, наилучший', review_date: '2017-05-24')
Card.create(original_text: 'read', translated_text: 'читать, прочитать', review_date: '2017-05-24')
Card.create(original_text: 'thinking', translated_text: 'размышление; мышление', review_date: '2017-05-24')
Card.create(original_text: 'inside', translated_text: 'внутренний; внутри', review_date: '2017-05-24')
Card.create(original_text: 'stay', translated_text: 'останавливаться', review_date: '2017-05-24')
Card.create(original_text: 'question', translated_text: 'вопрос', review_date: '2017-05-24')
Card.create(original_text: 'full', translated_text: 'полный', review_date: '2017-05-24')
Card.create(original_text: 'cold', translated_text: 'холодный', review_date: '2017-05-24')
Card.create(original_text: 'die', translated_text: 'умирать', review_date: '2017-05-24')
Card.create(original_text: 'sir', translated_text: 'сэр, господин', review_date: '2017-05-24')
Card.create(original_text: 'case', translated_text: 'случай; обстоятельство', review_date: '2017-05-24')
Card.create(original_text: 'ran', translated_text: 'бегал', review_date: '2017-05-24')
Card.create(original_text: 'sometimes', translated_text: 'иногда, временами', review_date: '2017-05-24')
Card.create(original_text: 'power', translated_text: 'сила, мощь', review_date: '2017-05-24')
Card.create(original_text: 'wish', translated_text: 'желать, хотеть, желание', review_date: '2017-05-24')
Card.create(original_text: 'dream', translated_text: 'мечта, сон', review_date: '2017-05-24')
Card.create(original_text: 'stand', translated_text: 'стоять; ставить;  стойка', review_date: '2017-05-24')
Card.create(original_text: 'son', translated_text: 'сын', review_date: '2017-05-24')
Card.create(original_text: 'herself', translated_text: 'себя, себе, собой', review_date: '2017-05-24')
Card.create(original_text: 'pretty', translated_text: 'милый, прелестный', review_date: '2017-05-24')
Card.create(original_text: 'paper', translated_text: 'бумага', review_date: '2017-05-24')
Card.create(original_text: 'shoulder', translated_text: 'плечо', review_date: '2017-05-24')
Card.create(original_text: 'care', translated_text: 'забота, беспокоиться', review_date: '2017-05-24')
Card.create(original_text: 'alone', translated_text: 'единственный, один', review_date: '2017-05-24')
Card.create(original_text: 'making', translated_text: 'создание, становление', review_date: '2017-05-24')
Card.create(original_text: 'near', translated_text: 'возле, ближний', review_date: '2017-05-24')
Card.create(original_text: 'finger', translated_text: 'палец (на руке)', review_date: '2017-05-24')
Card.create(original_text: 'hold', translated_text: 'держать; владеть; вмещать', review_date: '2017-05-24')
Card.create(original_text: 'return', translated_text: 'возвращаться', review_date: '2017-05-24')
Card.create(original_text: 'fact', translated_text: 'факт; событие; случай', review_date: '2017-05-24')
Card.create(original_text: 'understand', translated_text: 'понимать', review_date: '2017-05-24')
Card.create(original_text: 'guess', translated_text: 'гадать, догадываться', review_date: '2017-05-24')
Card.create(original_text: 'table', translated_text: 'стол', review_date: '2017-05-24')
Card.create(original_text: 'dear', translated_text: 'дорогой, милый, любимый', review_date: '2017-05-24')
Card.create(original_text: 'trying', translated_text: 'трудный, тяжёлый', review_date: '2017-05-24')
Card.create(original_text: 'fell', translated_text: 'падал, упал', review_date: '2017-05-24')
Card.create(original_text: 'floor', translated_text: 'пол; этаж', review_date: '2017-05-24')
Card.create(original_text: 'mile', translated_text: 'миля', review_date: '2017-05-24')
Card.create(original_text: 'probably', translated_text: 'вероятно, наверное', review_date: '2017-05-24')
Card.create(original_text: 'type', translated_text: 'тип', review_date: '2017-05-24')
Card.create(original_text: 'deep', translated_text: 'глубокий', review_date: '2017-05-24')
Card.create(original_text: 'glass', translated_text: 'стекло, стакан, бокал', review_date: '2017-05-24')
Card.create(original_text: 'standing', translated_text: 'репутация; ранг, стоящий', review_date: '2017-05-24')
Card.create(original_text: 'trouble', translated_text: 'беспокойство, волнение', review_date: '2017-05-24')
Card.create(original_text: 'however', translated_text: 'однако, тем не менее', review_date: '2017-05-24')
Card.create(original_text: 'taken', translated_text: 'прич. прош. вр. от take', review_date: '2017-05-24')
Card.create(original_text: 'hey', translated_text: 'здорово!, привет!, эй!', review_date: '2017-05-24')
Card.create(original_text: 'sort', translated_text: 'род, сорт, тип', review_date: '2017-05-24')
Card.create(original_text: 'lay', translated_text: 'класть, положить', review_date: '2017-05-24')
Card.create(original_text: 'town', translated_text: 'город; городок', review_date: '2017-05-24')
Card.create(original_text: 'sleep', translated_text: 'сон; дремота', review_date: '2017-05-24')
Card.create(original_text: 'school', translated_text: 'школа', review_date: '2017-05-24')
Card.create(original_text: 'lost', translated_text: 'потерянный, потерявшийся', review_date: '2017-05-24')
Card.create(original_text: 'green', translated_text: 'зелёный', review_date: '2017-05-24')
Card.create(original_text: 'gonna', translated_text: 'собираться (что-л. сделать)', review_date: '2017-05-24')
Card.create(original_text: 'lip', translated_text: 'губа', review_date: '2017-05-24')
Card.create(original_text: 'round', translated_text: 'круглый', review_date: '2017-05-24')
Card.create(original_text: 'clear', translated_text: 'ясно, чётко, чистый', review_date: '2017-05-24')
Card.create(original_text: 'having', translated_text: 'владение, обладание', review_date: '2017-05-24')
Card.create(original_text: 'scream', translated_text: 'крик, вопить', review_date: '2017-05-24')
Card.create(original_text: 'touch', translated_text: 'касаться, трогать', review_date: '2017-05-24')
Card.create(original_text: 'blue', translated_text: 'голубой; лазурный; синий', review_date: '2017-05-24')
Card.create(original_text: 'hundred', translated_text: 'сто', review_date: '2017-05-24')
Card.create(original_text: 'known', translated_text: 'прич. прош. вр. от know', review_date: '2017-05-24')
Card.create(original_text: 'running', translated_text: 'бегающий, беготня', review_date: '2017-05-24')
Card.create(original_text: 'large', translated_text: 'большой, крупный', review_date: '2017-05-24')
Card.create(original_text: 'surprise', translated_text: 'удивление', review_date: '2017-05-24')
Card.create(original_text: 'beside', translated_text: 'рядом с; близ, около', review_date: '2017-05-24')
Card.create(original_text: 'talking', translated_text: 'разговор, говорящий', review_date: '2017-05-24')
Card.create(original_text: 'ten', translated_text: 'десять', review_date: '2017-05-24')
Card.create(original_text: 'less', translated_text: 'меньший, меньше', review_date: '2017-05-24')
Card.create(original_text: 'letter', translated_text: 'буква', review_date: '2017-05-24')
Card.create(original_text: 'twenty', translated_text: 'двадцать', review_date: '2017-05-24')
Card.create(original_text: 'snow', translated_text: 'снег', review_date: '2017-05-24')
Card.create(original_text: 'kept', translated_text: 'прош. вр., прич. прош. вр. от keep', review_date: '2017-05-24')
Card.create(original_text: 'brought', translated_text: 'прош. вр., прич. прош. вр. от bring', review_date: '2017-05-24')
Card.create(original_text: 'someone', translated_text: 'кто-нибудь, кто-то', review_date: '2017-05-24')
Card.create(original_text: 'past', translated_text: 'прошлое; прошедшее', review_date: '2017-05-24')
Card.create(original_text: 'country', translated_text: 'страна', review_date: '2017-05-24')
Card.create(original_text: 'leg', translated_text: 'нога (от бедра до ступни)', review_date: '2017-05-24')
Card.create(original_text: 'pick', translated_text: 'собирать, снимать; рвать', review_date: '2017-05-24')
Card.create(original_text: 'brother', translated_text: 'брат', review_date: '2017-05-24')
Card.create(original_text: 'wood', translated_text: 'лес, древесина', review_date: '2017-05-24')
Card.create(original_text: 'women', translated_text: 'женщины', review_date: '2017-05-24')
Card.create(original_text: 'wrong', translated_text: 'неправильный, неверный', review_date: '2017-05-24')
Card.create(original_text: 'sense', translated_text: 'чувство; ощущение', review_date: '2017-05-24')
Card.create(original_text: 'hurt', translated_text: 'ушиб; рана; травма', review_date: '2017-05-24')
Card.create(original_text: 'cut', translated_text: 'резать', review_date: '2017-05-24')
Card.create(original_text: 'drop', translated_text: 'капать, опускать', review_date: '2017-05-24')
Card.create(original_text: 'ring', translated_text: 'кольцо, ринг, звенеть', review_date: '2017-05-24')
Card.create(original_text: 'sitting', translated_text: 'заседание, собрание', review_date: '2017-05-24')
Card.create(original_text: 'true', translated_text: 'верный, правильный', review_date: '2017-05-24')
Card.create(original_text: 'poor', translated_text: 'бедный, малоимущий', review_date: '2017-05-24')
Card.create(original_text: 'order', translated_text: 'исправность, порядок', review_date: '2017-05-24')
Card.create(original_text: 'fang', translated_text: 'клык, зуб, крюк', review_date: '2017-05-24')
Card.create(original_text: 'child', translated_text: 'ребёнок; дитя', review_date: '2017-05-24')
Card.create(original_text: 'ready', translated_text: 'готовый', review_date: '2017-05-24')
Card.create(original_text: 'land', translated_text: 'земля, суша', review_date: '2017-05-24')
Card.create(original_text: 'hot', translated_text: 'горячий; жаркий', review_date: '2017-05-24')
Card.create(original_text: 'speak', translated_text: 'говорить, разговаривать', review_date: '2017-05-24')
Card.create(original_text: 'children', translated_text: 'дети', review_date: '2017-05-24')
Card.create(original_text: 'fine', translated_text: 'хороший, прекрасный, отлично', review_date: '2017-05-24')
Card.create(original_text: 'given', translated_text: 'нечто данное, исходное, данный', review_date: '2017-05-24')
Card.create(original_text: 'able', translated_text: 'способный', review_date: '2017-05-24')
Card.create(original_text: 'become', translated_text: 'становиться, делаться', review_date: '2017-05-24')
Card.create(original_text: 'low', translated_text: 'низкий, невысокий', review_date: '2017-05-24')
Card.create(original_text: 'person', translated_text: 'человек; личность,', review_date: '2017-05-24')
Card.create(original_text: 'evening', translated_text: 'вечер', review_date: '2017-05-24')
Card.create(original_text: 'outside', translated_text: 'внешняя, наружная часть', review_date: '2017-05-24')
Card.create(original_text: 'listen', translated_text: 'слушать; выслушивать', review_date: '2017-05-24')
Card.create(original_text: 'wind', translated_text: 'ветер', review_date: '2017-05-24')
Card.create(original_text: 'smell', translated_text: 'запах; аромат', review_date: '2017-05-24')
Card.create(original_text: 'chair', translated_text: 'стул; кресло', review_date: '2017-05-24')
Card.create(original_text: 'six', translated_text: 'шесть', review_date: '2017-05-24')
Card.create(original_text: 'forward', translated_text: 'вперёд! передний', review_date: '2017-05-24')
Card.create(original_text: 'hill', translated_text: 'возвышенность, холм', review_date: '2017-05-24')
Card.create(original_text: 'reason', translated_text: 'причина, повод, основание', review_date: '2017-05-24')
Card.create(original_text: 'ground', translated_text: 'земля', review_date: '2017-05-24')
Card.create(original_text: 'above', translated_text: 'наверху, вверху; выше', review_date: '2017-05-24')
Card.create(original_text: 'chance', translated_text: 'шанс, возможность', review_date: '2017-05-24')
Card.create(original_text: 'story', translated_text: 'повесть, рассказ', review_date: '2017-05-24')
Card.create(original_text: 'late', translated_text: 'поздний; поздно', review_date: '2017-05-24')
Card.create(original_text: 'saying', translated_text: 'высказывание, поговорка', review_date: '2017-05-24')
Card.create(original_text: 'star', translated_text: 'звезда', review_date: '2017-05-24')
Card.create(original_text: 'husband', translated_text: 'муж, супруг', review_date: '2017-05-24')
Card.create(original_text: 'ago', translated_text: 'тому назад', review_date: '2017-05-24')
Card.create(original_text: 'except', translated_text: 'исключать, за исключением', review_date: '2017-05-24')
Card.create(original_text: 'lord', translated_text: 'господин, владыка', review_date: '2017-05-24')
Card.create(original_text: 'sorry', translated_text: 'огорчённый, сожалеющий', review_date: '2017-05-24')
Card.create(original_text: 'number', translated_text: 'число; сумма, цифра', review_date: '2017-05-24')
Card.create(original_text: 'roll', translated_text: 'катиться, вращение', review_date: '2017-05-24')
Card.create(original_text: '', translated_text: 'дольше', review_date: '2017-05-24')
Card.create(original_text: 'rock', translated_text: 'скала, камень', review_date: '2017-05-24')
Card.create(original_text: 'learn', translated_text: 'учиться; учить', review_date: '2017-05-24')
Card.create(original_text: 'often', translated_text: 'часто, много раз', review_date: '2017-05-24')
Card.create(original_text: 'although', translated_text: 'хотя, если бы даже', review_date: '2017-05-24')
Card.create(original_text: 'shit', translated_text: 'дерьмо, вздор, чёрт!, блин!', review_date: '2017-05-24')
Card.create(original_text: 'sister', translated_text: 'сестра', review_date: '2017-05-24')
Card.create(original_text: 'strange', translated_text: 'чужой, странный', review_date: '2017-05-24')
Card.create(original_text: 'bring', translated_text: 'приносить, привозить', review_date: '2017-05-24')
Card.create(original_text: 'pain', translated_text: 'боль, горе', review_date: '2017-05-24')
Card.create(original_text: 'nod', translated_text: 'кивок, кивать', review_date: '2017-05-24')
Card.create(original_text: 'fall', translated_text: 'падать, осень (амер.)', review_date: '2017-05-24')
Card.create(original_text: 'finally', translated_text: 'окончательно', review_date: '2017-05-24')
Card.create(original_text: 'among', translated_text: 'между, посреди', review_date: '2017-05-24')
Card.create(original_text: 'cause', translated_text: 'причина, основание, потому что', review_date: '2017-05-24')
Card.create(original_text: 'afraid', translated_text: 'испуганный, напуганный', review_date: '2017-05-24')
Card.create(original_text: 'notice', translated_text: 'сообщение, уведомление, замечать', review_date: '2017-05-24')
Card.create(original_text: 'sun', translated_text: 'солнце', review_date: '2017-05-24')
Card.create(original_text: 'month', translated_text: 'месяц', review_date: '2017-05-24')
Card.create(original_text: 'shut', translated_text: 'закрывать, запирать, засов', review_date: '2017-05-24')
Card.create(original_text: 'box', translated_text: 'ящик, коробка', review_date: '2017-05-24')
Card.create(original_text: 'hell', translated_text: 'ад', review_date: '2017-05-24')
Card.create(original_text: 'office', translated_text: 'офис', review_date: '2017-05-24')
Card.create(original_text: 'during', translated_text: 'в течение, в продолжение', review_date: '2017-05-24')
Card.create(original_text: 'wonder', translated_text: 'удивление, удивляться', review_date: '2017-05-24')
Card.create(original_text: 'beyond', translated_text: 'за, по ту сторону, далеко', review_date: '2017-05-24')
Card.create(original_text: 'became', translated_text: 'становился, делался', review_date: '2017-05-24')
Card.create(original_text: 'shadow', translated_text: 'тень', review_date: '2017-05-24')
Card.create(original_text: 'slowly', translated_text: 'медленно', review_date: '2017-05-24')
Card.create(original_text: 'instead', translated_text: 'вместо; взамен', review_date: '2017-05-24')
Card.create(original_text: 'ear', translated_text: 'ухо', review_date: '2017-05-24')
Card.create(original_text: 'picture', translated_text: 'картина; рисунок, фотография', review_date: '2017-05-24')
Card.create(original_text: 'interest', translated_text: 'интерес', review_date: '2017-05-24')
Card.create(original_text: 'cannot', translated_text: 'не могу, не мочь', review_date: '2017-05-24')
Card.create(original_text: 'present', translated_text: 'текущий момент; настоящее время', review_date: '2017-05-24')
Card.create(original_text: 'bit', translated_text: 'кусочек; частица', review_date: '2017-05-24')
Card.create(original_text: 'living', translated_text: 'образ жизни, жизнь, живущий,', review_date: '2017-05-24')
Card.create(original_text: 'remain', translated_text: 'оставаться', review_date: '2017-05-24')
Card.create(original_text: 'appear', translated_text: 'показываться; появляться', review_date: '2017-05-24')
Card.create(original_text: 'store', translated_text: 'магазин, запас, резерв', review_date: '2017-05-24')
Card.create(original_text: 'marry', translated_text: 'жениться', review_date: '2017-05-24')
Card.create(original_text: 'rather', translated_text: 'лучше, охотнее', review_date: '2017-05-24')
Card.create(original_text: 'doubt', translated_text: 'сомнение, сомневаться', review_date: '2017-05-24')
Card.create(original_text: 'teeth', translated_text: 'зубы', review_date: '2017-05-24')
Card.create(original_text: 'force', translated_text: 'сила', review_date: '2017-05-24')
Card.create(original_text: 'spoke', translated_text: 'говорил, сказал', review_date: '2017-05-24')
Card.create(original_text: 'finish', translated_text: 'конец, окончание, заканчивать', review_date: '2017-05-24')
Card.create(original_text: 'indeed', translated_text: 'в самом деле, действительно', review_date: '2017-05-24')
Card.create(original_text: 'seat', translated_text: 'сиденье, место', review_date: '2017-05-24')
Card.create(original_text: 'nor', translated_text: 'также не, тоже не', review_date: '2017-05-24')
Card.create(original_text: 'save', translated_text: 'спасать', review_date: '2017-05-24')
Card.create(original_text: 'job', translated_text: 'работа, труд', review_date: '2017-05-24')
Card.create(original_text: 'war', translated_text: 'война', review_date: '2017-05-24')
Card.create(original_text: 'dress', translated_text: 'одежда, платье', review_date: '2017-05-24')
Card.create(original_text: 'cover', translated_text: 'накрывать, покрывать, крышка, обложка', review_date: '2017-05-24')
Card.create(original_text: 'realize', translated_text: 'выполнять, реализовывать', review_date: '2017-05-24')
Card.create(original_text: 'gun', translated_text: 'орудие, пушка, пистолет, револьвер', review_date: '2017-05-24')
Card.create(original_text: 'heavy', translated_text: 'тяжёлый, крупный', review_date: '2017-05-24')
Card.create(original_text: 'waiting', translated_text: 'ожидание, выжидание', review_date: '2017-05-24')
Card.create(original_text: 'fellow', translated_text: 'человек, парень', review_date: '2017-05-24')
Card.create(original_text: 'sign', translated_text: 'знак; символ, подписывать', review_date: '2017-05-24')
Card.create(original_text: 'stuff', translated_text: 'материал, состав, вещество', review_date: '2017-05-24')
Card.create(original_text: 'decide', translated_text: 'решать, принимать решение', review_date: '2017-05-24')
Card.create(original_text: 'expect', translated_text: 'ждать, ожидать', review_date: '2017-05-24')
Card.create(original_text: 'hit', translated_text: 'ударять; поражать', review_date: '2017-05-24')
Card.create(original_text: 'corner', translated_text: 'угол', review_date: '2017-05-24')
Card.create(original_text: 'beaver', translated_text: 'бобр, бобёр; женские половые органы (киска)', review_date: '2017-05-24')
Card.create(original_text: 'king', translated_text: 'король', review_date: '2017-05-24')
Card.create(original_text: 'happy', translated_text: 'счастливый, довольный', review_date: '2017-05-24')
Card.create(original_text: 'phone', translated_text: 'телефон', review_date: '2017-05-24')
Card.create(original_text: 'several', translated_text: 'некоторые, несколько', review_date: '2017-05-24')
Card.create(original_text: 'city', translated_text: 'город', review_date: '2017-05-24')
Card.create(original_text: 'news', translated_text: 'новости', review_date: '2017-05-24')
Card.create(original_text: 'summer', translated_text: 'лето', review_date: '2017-05-24')
Card.create(original_text: 'different', translated_text: 'другой, отличный', review_date: '2017-05-24')
Card.create(original_text: 'sit', translated_text: 'сидеть; садиться', review_date: '2017-05-24')
Card.create(original_text: 'actually', translated_text: 'фактически, на самом деле', review_date: '2017-05-24')
Card.create(original_text: 'caught', translated_text: 'прош. вр., прич. прош. вр. от catch', review_date: '2017-05-24')
Card.create(original_text: 'taking', translated_text: 'захват, взятие', review_date: '2017-05-24')
Card.create(original_text: 'broken', translated_text: 'разбитый, сломанный', review_date: '2017-05-24')
Card.create(original_text: 'early', translated_text: 'начальный, ранний', review_date: '2017-05-24')
Card.create(original_text: 'bright', translated_text: 'яркий; блестящий', review_date: '2017-05-24')
Card.create(original_text: 'daughter', translated_text: 'дочь', review_date: '2017-05-24')
Card.create(original_text: 'enter', translated_text: 'вход, входить', review_date: '2017-05-24')
Card.create(original_text: 'shot', translated_text: 'выстрел', review_date: '2017-05-24')
Card.create(original_text: 'carry', translated_text: 'нести, носить', review_date: '2017-05-24')
Card.create(original_text: 'foot', translated_text: 'ступня', review_date: '2017-05-24')
Card.create(original_text: 'scare', translated_text: 'пугать; испугать', review_date: '2017-05-24')
Card.create(original_text: 'tad', translated_text: 'ребёнок, капелька, чуточка', review_date: '2017-05-24')
Card.create(original_text: 'holding', translated_text: 'вклад, закрепление, удерживание', review_date: '2017-05-24')
Card.create(original_text: 'human', translated_text: 'людской, человеческий', review_date: '2017-05-24')
Card.create(original_text: 'whatever', translated_text: 'какой бы ни; любой', review_date: '2017-05-24')
Card.create(original_text: 'yourself', translated_text: 'себя, себе, собой', review_date: '2017-05-24')
Card.create(original_text: 'form', translated_text: 'форма, вид', review_date: '2017-05-24')
Card.create(original_text: 'worry', translated_text: 'надоедать; докучать', review_date: '2017-05-24')
Card.create(original_text: 'shook', translated_text: 'тряс, встряхивал', review_date: '2017-05-24')
Card.create(original_text: 'exactly', translated_text: 'в точности; точно', review_date: '2017-05-24')
Card.create(original_text: 'neck', translated_text: 'шея', review_date: '2017-05-24')
Card.create(original_text: 'fill', translated_text: 'наполнять', review_date: '2017-05-24')
Card.create(original_text: 'certain', translated_text: 'точный, определённый', review_date: '2017-05-24')
Card.create(original_text: 'nose', translated_text: 'нос', review_date: '2017-05-24')
Card.create(original_text: 'brutal', translated_text: 'жестокий, горький, брутальный', review_date: '2017-05-24')
Card.create(original_text: 'continue', translated_text: 'продолжать', review_date: '2017-05-24')
Card.create(original_text: 'drink', translated_text: 'пить', review_date: '2017-05-24')
Card.create(original_text: 'free', translated_text: 'свободный, вольный', review_date: '2017-05-24')
Card.create(original_text: 'sky', translated_text: 'небо', review_date: '2017-05-24')
Card.create(original_text: 'mark', translated_text: 'марка, маркировать', review_date: '2017-05-24')
Card.create(original_text: 'company', translated_text: 'общество, компания', review_date: '2017-05-24')
Card.create(original_text: 'breath', translated_text: 'дыхание; вздох', review_date: '2017-05-24')
Card.create(original_text: 'reply', translated_text: 'ответ, отклик', review_date: '2017-05-24')
Card.create(original_text: 'fat', translated_text: 'толстый, жирный', review_date: '2017-05-24')
Card.create(original_text: 'park', translated_text: 'парк, парковка', review_date: '2017-05-24')
Card.create(original_text: 'rose', translated_text: 'роза, розовый', review_date: '2017-05-24')
Card.create(original_text: 'whose', translated_text: 'чей, чьё, чьи, чья', review_date: '2017-05-24')
Card.create(original_text: 'figure', translated_text: 'фигура', review_date: '2017-05-24')
Card.create(original_text: 'lie', translated_text: 'ложь, лгать', review_date: '2017-05-24')
Card.create(original_text: 'act', translated_text: 'действовать, дело, поступок', review_date: '2017-05-24')
Card.create(original_text: 'anyway', translated_text: 'как бы то ни было, в любом случае', review_date: '2017-05-24')
Card.create(original_text: 'cross', translated_text: 'крест, пересекать', review_date: '2017-05-24')
Card.create(original_text: 'master', translated_text: 'главный, старший; мастер', review_date: '2017-05-24')
Card.create(original_text: 'game', translated_text: 'игра', review_date: '2017-05-24')
Card.create(original_text: 'pocket', translated_text: 'карман, мешочек', review_date: '2017-05-24')
Card.create(original_text: 'stone', translated_text: 'камень', review_date: '2017-05-24')
Card.create(original_text: 'strong', translated_text: 'сильный, сильно', review_date: '2017-05-24')
Card.create(original_text: 'russian', translated_text: 'русский', review_date: '2017-05-24')
Card.create(original_text: 'horse', translated_text: 'лошадь', review_date: '2017-05-24')
Card.create(original_text: 'baby', translated_text: 'ребёнок, младенец', review_date: '2017-05-24')
Card.create(original_text: 'knee', translated_text: 'колено', review_date: '2017-05-24')
Card.create(original_text: 'police', translated_text: 'полиция', review_date: '2017-05-24')
Card.create(original_text: 'silence', translated_text: 'тишина, безмолвие', review_date: '2017-05-24')
Card.create(original_text: 'watching', translated_text: 'наблюдение', review_date: '2017-05-24')
Card.create(original_text: 'afternoon', translated_text: 'время после полудня, дневное время', review_date: '2017-05-24')
Card.create(original_text: 'dollar', translated_text: 'доллар', review_date: '2017-05-24')
Card.create(original_text: 'eat', translated_text: 'есть', review_date: '2017-05-24')
Card.create(original_text: 'deal', translated_text: 'сделка, соглашение, раздача', review_date: '2017-05-24')
Card.create(original_text: 'fast', translated_text: 'быстро, быстрый, скорый', review_date: '2017-05-24')
Card.create(original_text: 'add', translated_text: 'прибавлять, добавлять', review_date: '2017-05-24')
Card.create(original_text: 'itself', translated_text: 'себя, себе, сам', review_date: '2017-05-24')
Card.create(original_text: 'none', translated_text: 'ничуть, никто', review_date: '2017-05-24')
Card.create(original_text: 'check', translated_text: 'проверять, контроль, чек', review_date: '2017-05-24')
Card.create(original_text: 'sonny', translated_text: 'сынок', review_date: '2017-05-24')
Card.create(original_text: 'cheek', translated_text: 'щека', review_date: '2017-05-24')
Card.create(original_text: 'meant', translated_text: 'прош. вр., прич. прош. вр. от mean', review_date: '2017-05-24')
Card.create(original_text: 'push', translated_text: 'толкать; пихать', review_date: '2017-05-24')
Card.create(original_text: 'nature', translated_text: 'природа', review_date: '2017-05-24')
Card.create(original_text: 'fucking', translated_text: 'проклятый, чёртов, офигенно', review_date: '2017-05-24')
Card.create(original_text: 'struck', translated_text: 'прош. вр., прич. прош. вр. от strike', review_date: '2017-05-24')
Card.create(original_text: 'tear', translated_text: 'рвать, разрывать, слеза', review_date: '2017-05-24')
Card.create(original_text: 'chapter', translated_text: 'глава (книги)', review_date: '2017-05-24')
Card.create(original_text: 'middle', translated_text: 'середина, центр, средний', review_date: '2017-05-24')
Card.create(original_text: 'note', translated_text: 'заметка, запись', review_date: '2017-05-24')
Card.create(original_text: 'crazy', translated_text: 'сумасшедший, безумный', review_date: '2017-05-24')
Card.create(original_text: 'sent', translated_text: 'послал, отправил', review_date: '2017-05-24')
Card.create(original_text: 'smoke', translated_text: 'курить, курение, дым', review_date: '2017-05-24')
Card.create(original_text: 'bird', translated_text: 'птица', review_date: '2017-05-24')
Card.create(original_text: 'raise', translated_text: 'поднимать', review_date: '2017-05-24')
Card.create(original_text: 'promise', translated_text: 'обещание, обещать', review_date: '2017-05-24')
Card.create(original_text: 'thousand', translated_text: 'тысяча', review_date: '2017-05-24')
Card.create(original_text: 'hall', translated_text: 'холл, вестибюль; фойе', review_date: '2017-05-24')
Card.create(original_text: 'nice', translated_text: 'хороший, приятный, милый', review_date: '2017-05-24')
Card.create(original_text: 'moving', translated_text: 'движение, перемещение', review_date: '2017-05-24')
Card.create(original_text: 'seeing', translated_text: 'видение, принимая во внимание', review_date: '2017-05-24')
Card.create(original_text: 'whom', translated_text: 'кого', review_date: '2017-05-24')
Card.create(original_text: 'law', translated_text: 'закон, право', review_date: '2017-05-24')
Card.create(original_text: 'meet', translated_text: 'встречаться, видеться', review_date: '2017-05-24')
Card.create(original_text: 'quiet', translated_text: 'тихий, бесшумный, спокойный,', review_date: '2017-05-24')
Card.create(original_text: 'sight', translated_text: 'зрение, вид; зрелище', review_date: '2017-05-24')
Card.create(original_text: 'throat', translated_text: 'горло, гортань; глотка', review_date: '2017-05-24')
Card.create(original_text: 'wide', translated_text: 'широкий', review_date: '2017-05-24')
Card.create(original_text: 'desire', translated_text: 'жаждать, очень хотеть', review_date: '2017-05-24')
Card.create(original_text: 'hole', translated_text: 'дыра; отверстие; прорезь', review_date: '2017-05-24')
Card.create(original_text: 'certainly', translated_text: 'конечно, естественно', review_date: '2017-05-24')
Card.create(original_text: 'terrible', translated_text: 'страшный, ужасный', review_date: '2017-05-24')
Card.create(original_text: 'earth', translated_text: 'земля, суша', review_date: '2017-05-24')
Card.create(original_text: 'kiss', translated_text: 'целовать, поцелуй', review_date: '2017-05-24')
Card.create(original_text: 'lock', translated_text: 'локон, замок, затвор', review_date: '2017-05-24')
Card.create(original_text: 'manner', translated_text: 'манера, поведение; метод', review_date: '2017-05-24')
Card.create(original_text: 'party', translated_text: 'партия, вечеринка', review_date: '2017-05-24')
Card.create(original_text: 'movie', translated_text: 'кинофильм, фильм', review_date: '2017-05-24')
Card.create(original_text: 'possible', translated_text: 'вероятный, возможный', review_date: '2017-05-24')
Card.create(original_text: 'kitchen', translated_text: 'кухня', review_date: '2017-05-24')
Card.create(original_text: 'piece', translated_text: 'кусок, штука', review_date: '2017-05-24')
Card.create(original_text: 'attention', translated_text: 'внимание, внимательность', review_date: '2017-05-24')
Card.create(original_text: 'silver', translated_text: 'серебро, серебряный', review_date: '2017-05-24')
Card.create(original_text: 'damn', translated_text: 'проклятие; ругательство', review_date: '2017-05-24')
Card.create(original_text: 'folk', translated_text: 'народный, люди', review_date: '2017-05-24')
Card.create(original_text: 'glance', translated_text: 'блеснуть, сверкнуть', review_date: '2017-05-24')
Card.create(original_text: 'themselves', translated_text: 'себя, себе, собой', review_date: '2017-05-24')
Card.create(original_text: 'laughing', translated_text: 'смех, хохот', review_date: '2017-05-24')
Card.create(original_text: 'pay', translated_text: 'платить', review_date: '2017-05-24')
Card.create(original_text: 'fuck', translated_text: 'трахать, трахаться', review_date: '2017-05-24')
Card.create(original_text: 'easy', translated_text: 'лёгкий, легко', review_date: '2017-05-24')
Card.create(original_text: 'west', translated_text: 'запад', review_date: '2017-05-24')
Card.create(original_text: 'whisper', translated_text: 'говорить шёпотом, шептать', review_date: '2017-05-24')
Card.create(original_text: 'today', translated_text: 'сегодня', review_date: '2017-05-24')
Card.create(original_text: 'telling', translated_text: 'сильный, эффектный', review_date: '2017-05-24')
Card.create(original_text: 'shirt', translated_text: 'рубашка; блуза; сорочка', review_date: '2017-05-24')
Card.create(original_text: 'ahead', translated_text: 'вперёд; впереди, будущий', review_date: '2017-05-24')
Card.create(original_text: 'till', translated_text: 'до, не раньше', review_date: '2017-05-24')
Card.create(original_text: 'walking', translated_text: 'ходьба, походка', review_date: '2017-05-24')
Card.create(original_text: 'edge', translated_text: 'край; грань, граница', review_date: '2017-05-24')
Card.create(original_text: 'empty', translated_text: 'пустой, полый', review_date: '2017-05-24')
Card.create(original_text: 'quickly', translated_text: 'быстро, скоро, поспешно', review_date: '2017-05-24')
Card.create(original_text: 'north', translated_text: 'север, северный', review_date: '2017-05-24')
Card.create(original_text: 'simply', translated_text: 'легко, просто; несложно', review_date: '2017-05-24')
Card.create(original_text: 'tire', translated_text: 'утомляться, уставать, шина', review_date: '2017-05-24')
Card.create(original_text: 'food', translated_text: 'пища, питание; еда', review_date: '2017-05-24')
Card.create(original_text: 'somehow', translated_text: 'как-нибудь, как-то', review_date: '2017-05-24')
Card.create(original_text: 'clock', translated_text: 'часы, время', review_date: '2017-05-24')
Card.create(original_text: 'nearly', translated_text: 'близко', review_date: '2017-05-24')
Card.create(original_text: 'bag', translated_text: 'мешок; сумка', review_date: '2017-05-24')
Card.create(original_text: 'clothes', translated_text: 'одежда, платье', review_date: '2017-05-24')
Card.create(original_text: 'south', translated_text: 'юг, южный', review_date: '2017-05-24')
Card.create(original_text: 'american', translated_text: 'американский', review_date: '2017-05-24')
Card.create(original_text: 'unite', translated_text: 'объединять, соединять', review_date: '2017-05-24')
Card.create(original_text: 'pleasure', translated_text: 'удовольствие', review_date: '2017-05-24')
Card.create(original_text: 'river', translated_text: 'река', review_date: '2017-05-24')
Card.create(original_text: 'problem', translated_text: 'проблема; задача', review_date: '2017-05-24')
Card.create(original_text: 'below', translated_text: 'внизу, ниже', review_date: '2017-05-24')
Card.create(original_text: 'break', translated_text: 'ломать, перерыв, пауза', review_date: '2017-05-24')
Card.create(original_text: 'couple', translated_text: 'пара, два, двое', review_date: '2017-05-24')
Card.create(original_text: 'report', translated_text: 'доклад, рапорт, докладывать', review_date: '2017-05-24')
Card.create(original_text: 'key', translated_text: 'ключ, клавиша, кнопка', review_date: '2017-05-24')
Card.create(original_text: 'shape', translated_text: 'форма, очертание, вид', review_date: '2017-05-24')
Card.create(original_text: 'within', translated_text: 'в, внутри', review_date: '2017-05-24')
Card.create(original_text: 'third', translated_text: 'третий, треть', review_date: '2017-05-24')
Card.create(original_text: 'anyone', translated_text: 'кто-нибудь, никто', review_date: '2017-05-24')
Card.create(original_text: 'count', translated_text: 'вычисление, счёт, считать', review_date: '2017-05-24')
Card.create(original_text: 'quick', translated_text: 'быстрый, скорый', review_date: '2017-05-24')
Card.create(original_text: 'seven', translated_text: 'семь', review_date: '2017-05-24')
Card.create(original_text: 'plan', translated_text: 'план; проект, планировать', review_date: '2017-05-24')
Card.create(original_text: 'tonight', translated_text: 'сегодня вечером, сегодня ночью', review_date: '2017-05-24')
Card.create(original_text: 'path', translated_text: 'тропинка; дорожка, путь', review_date: '2017-05-24')
Card.create(original_text: 'yellow', translated_text: 'жёлтый', review_date: '2017-05-24')
Card.create(original_text: 'drive', translated_text: 'ездить; ехать, водить', review_date: '2017-05-24')
Card.create(original_text: 'huge', translated_text: 'большой, гигантский', review_date: '2017-05-24')
Card.create(original_text: 'bank', translated_text: 'банк', review_date: '2017-05-24')
Card.create(original_text: 'control', translated_text: 'управление, контроль', review_date: '2017-05-24')
Card.create(original_text: 'memory', translated_text: 'память', review_date: '2017-05-24')
Card.create(original_text: 'working', translated_text: 'обработка, работающий', review_date: '2017-05-24')
Card.create(original_text: 'brain', translated_text: 'мозг', review_date: '2017-05-24')
Card.create(original_text: 'goes', translated_text: 'идёт', review_date: '2017-05-24')
Card.create(original_text: 'met', translated_text: 'встречал, встречался', review_date: '2017-05-24')
Card.create(original_text: 'professor', translated_text: 'профессор, преподаватель', review_date: '2017-05-24')
Card.create(original_text: 'mine', translated_text: 'мой; моя; моё, рудник, мина', review_date: '2017-05-24')
Card.create(original_text: 'wearing', translated_text: 'предназначенный для носки', review_date: '2017-05-24')
Card.create(original_text: 'grew', translated_text: 'рос, вырастил', review_date: '2017-05-24')
Card.create(original_text: 'animal', translated_text: 'животное; зверь', review_date: '2017-05-24')
Card.create(original_text: 'glad', translated_text: 'рад, доволен, счастлив', review_date: '2017-05-24')
Card.create(original_text: 'hurry', translated_text: 'торопиться, спешить, спешка', review_date: '2017-05-24')
Card.create(original_text: 'silent', translated_text: 'безмолвный,  бесшумный', review_date: '2017-05-24')
Card.create(original_text: 'thirty', translated_text: 'тридцать', review_date: '2017-05-24')
Card.create(original_text: 'hardly', translated_text: 'едва, еле, насилу', review_date: '2017-05-24')
Card.create(original_text: 'mountain', translated_text: 'гора', review_date: '2017-05-24')
Card.create(original_text: 'ball', translated_text: 'мяч, шар, бал, танцы', review_date: '2017-05-24')
Card.create(original_text: 'thin', translated_text: 'тонкий, худой', review_date: '2017-05-24')
Card.create(original_text: 'direction', translated_text: 'направление, указание', review_date: '2017-05-24')
Card.create(original_text: 'drew', translated_text: 'рисовал, чертил', review_date: '2017-05-24')
Card.create(original_text: 'ham', translated_text: 'ветчина, окорок, бедро', review_date: '2017-05-24')
Card.create(original_text: 'important', translated_text: 'важный, значительный', review_date: '2017-05-24')
Card.create(original_text: 'led', translated_text: 'прош. вр., прич. прош. вр. от lead', review_date: '2017-05-24')
Card.create(original_text: 'grab', translated_text: 'схватывать, хватать', review_date: '2017-05-24')
Card.create(original_text: 'receive', translated_text: 'получить', review_date: '2017-05-24')
Card.create(original_text: 'wolf', translated_text: 'волк', review_date: '2017-05-24')
Card.create(original_text: 'knock', translated_text: 'стучать, барабанить', review_date: '2017-05-24')
Card.create(original_text: 'slip', translated_text: 'скользить', review_date: '2017-05-24')
Card.create(original_text: 'loud', translated_text: 'громкий; звучный', review_date: '2017-05-24')
Card.create(original_text: 'brown', translated_text: 'коричневый; бурый', review_date: '2017-05-24')
Card.create(original_text: 'eight', translated_text: 'восемь', review_date: '2017-05-24')
Card.create(original_text: 'wheel', translated_text: 'колесо', review_date: '2017-05-24')
Card.create(original_text: 'beautiful', translated_text: 'красивый, привлекательный', review_date: '2017-05-24')
Card.create(original_text: 'begin', translated_text: 'начинать, начинаться', review_date: '2017-05-24')
Card.create(original_text: 'hate', translated_text: 'ненависть, ненавидеть', review_date: '2017-05-24')
Card.create(original_text: 'lying', translated_text: 'лживый, ложный', review_date: '2017-05-24')
Card.create(original_text: 'retrieve', translated_text: 'отыскать, поиск', review_date: '2017-05-24')
Card.create(original_text: 'secret', translated_text: 'секрет, тайна', review_date: '2017-05-24')
Card.create(original_text: 'wild', translated_text: 'дикий (о животных); дикорастущий', review_date: '2017-05-24')
Card.create(original_text: 'color', translated_text: 'цвет; оттенок', review_date: '2017-05-24')
Card.create(original_text: 'fair', translated_text: 'честный, справедливый', review_date: '2017-05-24')
Card.create(original_text: 'east', translated_text: 'восток', review_date: '2017-05-24')
Card.create(original_text: 'wing', translated_text: 'крыло', review_date: '2017-05-24')
Card.create(original_text: 'main', translated_text: 'главная часть; основное', review_date: '2017-05-24')
Card.create(original_text: 'visit', translated_text: 'посещение, визит', review_date: '2017-05-24')
Card.create(original_text: 'following', translated_text: 'следующий (во времени и в пространстве); последующий', review_date: '2017-05-24')
Card.create(original_text: 'sharp', translated_text: 'острый, ровно, точно', review_date: '2017-05-24')
Card.create(original_text: 'subject', translated_text: 'тема, предмет разговора', review_date: '2017-05-24')
Card.create(original_text: 'understood', translated_text: 'прош. вр., прич. прош. вр. от understand', review_date: '2017-05-24')
Card.create(original_text: 'lake', translated_text: 'озеро', review_date: '2017-05-24')
Card.create(original_text: 'page', translated_text: 'лист, страница', review_date: '2017-05-24')
Card.create(original_text: 'skin', translated_text: 'кожа, мех, шкура', review_date: '2017-05-24')
Card.create(original_text: 'station', translated_text: 'пункт, станция', review_date: '2017-05-24')
Card.create(original_text: 'study', translated_text: 'учёба, изучение', review_date: '2017-05-24')
Card.create(original_text: 'spring', translated_text: 'весна, прыгать, скакать', review_date: '2017-05-24')
Card.create(original_text: 'account', translated_text: 'счёт (в банке)', review_date: '2017-05-24')
Card.create(original_text: 'building', translated_text: 'здание, постройка, сооружение', review_date: '2017-05-24')
Card.create(original_text: 'desk', translated_text: 'письменный, рабочий стол, парта', review_date: '2017-05-24')
Card.create(original_text: 'hung', translated_text: 'прош. вр., прич. прош. вр. от hang', review_date: '2017-05-24')
Card.create(original_text: 'fifty', translated_text: 'пятьдесят', review_date: '2017-05-24')
Card.create(original_text: 'gold', translated_text: 'золото', review_date: '2017-05-24')
Card.create(original_text: 'neither', translated_text: 'никакой, ни тот, ни другой', review_date: '2017-05-24')
Card.create(original_text: 'send', translated_text: 'посылать, отправлять', review_date: '2017-05-24')
Card.create(original_text: 'stick', translated_text: 'палка; прут, трость', review_date: '2017-05-24')
Card.create(original_text: 'straight', translated_text: 'прямой, честный, прямо', review_date: '2017-05-24')
Card.create(original_text: 'darkness', translated_text: 'темнота, мрак; ночь', review_date: '2017-05-24')
Card.create(original_text: 'experience', translated_text: 'опыт, случай, событие', review_date: '2017-05-24')
Card.create(original_text: 'bar', translated_text: 'брусок, кусок, планка, бар, прилавок', review_date: '2017-05-24')
Card.create(original_text: 'imagine', translated_text: 'воображать, представлять себе', review_date: '2017-05-24')
Card.create(original_text: 'ship', translated_text: 'корабль; судно', review_date: '2017-05-24')
Card.create(original_text: 'thus', translated_text: 'так, таким образом', review_date: '2017-05-24')
Card.create(original_text: 'forget', translated_text: 'забывать о (чём-л.)', review_date: '2017-05-24')
Card.create(original_text: 'nine', translated_text: 'девять', review_date: '2017-05-24')
Card.create(original_text: 'agree', translated_text: 'соглашаться', review_date: '2017-05-24')
Card.create(original_text: 'gotten', translated_text: 'прич. прош. вр. от get', review_date: '2017-05-24')
Card.create(original_text: 'interior', translated_text: 'внутренняя часть, внутренний', review_date: '2017-05-24')
Card.create(original_text: 'rain', translated_text: 'дождь', review_date: '2017-05-24')
Card.create(original_text: 'block', translated_text: 'квартал (города), заграждать, преграждать', review_date: '2017-05-24')
Card.create(original_text: 'fix', translated_text: 'устанавливать; прикреплять', review_date: '2017-05-24')
Card.create(original_text: 'turning', translated_text: 'отклонение, изменение, поворот', review_date: '2017-05-24')
Card.create(original_text: 'warm', translated_text: 'тёплый', review_date: '2017-05-24')
Card.create(original_text: 'whether', translated_text: 'ли, любой из двух', review_date: '2017-05-24')
Card.create(original_text: 'dinner', translated_text: 'обед, обедать', review_date: '2017-05-24')
Card.create(original_text: 'somewhere', translated_text: 'где-то, где-нибудь; куда-нибудь', review_date: '2017-05-24')
Card.create(original_text: 'space', translated_text: 'пространство', review_date: '2017-05-24')
Card.create(original_text: 'chest', translated_text: 'ящик; коробка, сундук', review_date: '2017-05-24')
Card.create(original_text: 'write', translated_text: 'писать, выписывать', review_date: '2017-05-24')
Card.create(original_text: 'rich', translated_text: 'богатый, состоятельный', review_date: '2017-05-24')
Card.create(original_text: 'pause', translated_text: 'пауза, перерыв; остановка', review_date: '2017-05-24')
Card.create(original_text: 'single', translated_text: 'один; единственный', review_date: '2017-05-24')
Card.create(original_text: 'yard', translated_text: 'ярд', review_date: '2017-05-24')
Card.create(original_text: 'further', translated_text: 'дальнейший, добавочный, дальше', review_date: '2017-05-24')
Card.create(original_text: 'leaving', translated_text: 'предоставление', review_date: '2017-05-24')
Card.create(original_text: 'soft', translated_text: 'мягкий', review_date: '2017-05-24')
Card.create(original_text: 'allow', translated_text: 'позволять, разрешать', review_date: '2017-05-24')
Card.create(original_text: 'onto', translated_text: 'на; в', review_date: '2017-05-24')
Card.create(original_text: 'pale', translated_text: 'бледный, бледнеть', review_date: '2017-05-24')
Card.create(original_text: 'tie', translated_text: 'галстук, узел; бант', review_date: '2017-05-24')
Card.create(original_text: 'beginning', translated_text: 'начало', review_date: '2017-05-24')
Card.create(original_text: 'ought', translated_text: 'выражает долженствование', review_date: '2017-05-24')
Card.create(original_text: 'stare', translated_text: 'вглядываться; уставиться', review_date: '2017-05-24')
Card.create(original_text: 'doctor', translated_text: 'врач, доктор', review_date: '2017-05-24')
Card.create(original_text: 'sweet', translated_text: 'сладкий, приятный, милый', review_date: '2017-05-24')
Card.create(original_text: 'grin', translated_text: 'скалить зубы, ухмыляться', review_date: '2017-05-24')
Card.create(original_text: 'escape', translated_text: 'бегство; побег, убежать', review_date: '2017-05-24')
Card.create(original_text: 'press', translated_text: 'жать, нажимать, печать, пресса', review_date: '2017-05-24')
Card.create(original_text: 'general', translated_text: 'главный, основной, генеральный, генерал', review_date: '2017-05-24')
Card.create(original_text: 'shout', translated_text: 'кричать, возглас, крик', review_date: '2017-05-24')
Card.create(original_text: 'aware', translated_text: 'знающий, осведомлённый', review_date: '2017-05-24')
Card.create(original_text: 'consider', translated_text: 'рассматривать, думать, полагать', review_date: '2017-05-24')
Card.create(original_text: 'grey', translated_text: 'серый, седой, пасмурный', review_date: '2017-05-24')
Card.create(original_text: 'card', translated_text: 'карта, карточка', review_date: '2017-05-24')
Card.create(original_text: 'cloud', translated_text: 'облако; туча', review_date: '2017-05-24')
Card.create(original_text: 'spot', translated_text: 'пятно, пятнышко; крапинка', review_date: '2017-05-24')
Card.create(original_text: 'situation', translated_text: 'обстановка, положение, ситуация, место', review_date: '2017-05-24')
Card.create(original_text: 'board', translated_text: 'доска; планка', review_date: '2017-05-24')
Card.create(original_text: 'clean', translated_text: 'чистый, опрятный', review_date: '2017-05-24')
Card.create(original_text: 'truth', translated_text: 'правда; истина', review_date: '2017-05-24')
Card.create(original_text: 'explain', translated_text: 'объяснять; раскрывать', review_date: '2017-05-24')
Card.create(original_text: 'lower', translated_text: 'нижний, низший', review_date: '2017-05-24')
Card.create(original_text: 'machine', translated_text: 'машина, механизм; станок', review_date: '2017-05-24')
Card.create(original_text: 'post', translated_text: 'почта, корреспонденция, пост', review_date: '2017-05-24')
Card.create(original_text: 'view', translated_text: 'вид; пейзаж, точка зрения, мнение', review_date: '2017-05-24')
Card.create(original_text: 'project', translated_text: 'проект, замысел, план', review_date: '2017-05-24')
Card.create(original_text: 'bottle', translated_text: 'бутылка, бутыль', review_date: '2017-05-24')
Card.create(original_text: 'broke', translated_text: 'ломал, разбивал, крушил', review_date: '2017-05-24')
Card.create(original_text: 'position', translated_text: 'положение, местоположение', review_date: '2017-05-24')
Card.create(original_text: 'sea', translated_text: 'море', review_date: '2017-05-24')
Card.create(original_text: 'field', translated_text: 'поле; луг', review_date: '2017-05-24')
Card.create(original_text: 'fresh', translated_text: 'свежий, натуральный', review_date: '2017-05-24')
Card.create(original_text: 'join', translated_text: 'соединять, объединять, присоединяться', review_date: '2017-05-24')
Card.create(original_text: 'worse', translated_text: 'хуже, худшее', review_date: '2017-05-24')
Card.create(original_text: 'fly', translated_text: 'муха, полёт', review_date: '2017-05-24')
Card.create(original_text: 'offer', translated_text: 'предлагать', review_date: '2017-05-24')
Card.create(original_text: 'rush', translated_text: 'бросаться, мчаться, нестись, бросок, напор', review_date: '2017-05-24')
Card.create(original_text: 'safe', translated_text: 'безопасный, сейф', review_date: '2017-05-24')
Card.create(original_text: 'jump', translated_text: 'прыгать, скакать', review_date: '2017-05-24')
Card.create(original_text: 'smiling', translated_text: 'улыбается', review_date: '2017-05-24')
Card.create(original_text: 'track', translated_text: 'след, отпечаток, курс, путь', review_date: '2017-05-24')
Card.create(original_text: 'bone', translated_text: 'кость', review_date: '2017-05-24')
Card.create(original_text: 'murder', translated_text: 'убийство', review_date: '2017-05-24')
Card.create(original_text: 'creature', translated_text: 'создание, творение', review_date: '2017-05-24')
Card.create(original_text: 'growing', translated_text: 'рост, выращивание', review_date: '2017-05-24')
Card.create(original_text: 'monster', translated_text: 'чудовище; изверг, монстр', review_date: '2017-05-24')
Card.create(original_text: 'system', translated_text: 'система, устройство', review_date: '2017-05-24')
Card.create(original_text: 'beat', translated_text: 'бить, колотить, удар', review_date: '2017-05-24')
Card.create(original_text: 'funny', translated_text: 'забавный, смешной', review_date: '2017-05-24')
Card.create(original_text: 'hospital', translated_text: 'больница,  госпиталь', review_date: '2017-05-24')
Card.create(original_text: 'playing', translated_text: 'играющий, игральный', review_date: '2017-05-24')
Card.create(original_text: 'service', translated_text: 'служба, обслуживание, сервис', review_date: '2017-05-24')
Card.create(original_text: 'common', translated_text: 'общий, всеобщий', review_date: '2017-05-24')
Card.create(original_text: 'giving', translated_text: 'дающий, давая', review_date: '2017-05-24')
Card.create(original_text: 'sudden', translated_text: 'внезапный, внезапно', review_date: '2017-05-24')
Card.create(original_text: 'usually', translated_text: 'обычно, обыкновенно', review_date: '2017-05-24')
Card.create(original_text: 'settle', translated_text: 'поселиться, обосноваться', review_date: '2017-05-24')
Card.create(original_text: 'slow', translated_text: 'медленный, тихий', review_date: '2017-05-24')
Card.create(original_text: 'threw', translated_text: 'бросал, кидал', review_date: '2017-05-24')
Card.create(original_text: 'train', translated_text: 'тренироваться, поезд, состав', review_date: '2017-05-24')
Card.create(original_text: 'unless', translated_text: 'если не; пока не', review_date: '2017-05-24')
Card.create(original_text: 'ass', translated_text: 'зад, задница, жопа', review_date: '2017-05-24')
Card.create(original_text: 'beneath', translated_text: 'внизу; ниже', review_date: '2017-05-24')
Card.create(original_text: 'discover', translated_text: 'обнаруживать, находить', review_date: '2017-05-24')
Card.create(original_text: 'tomorrow', translated_text: 'завтра', review_date: '2017-05-24')
Card.create(original_text: 'bear', translated_text: 'носить, нести, медведь', review_date: '2017-05-24')
Card.create(original_text: 'cool', translated_text: 'прохладный, свежий, крутой, клёвый', review_date: '2017-05-24')
Card.create(original_text: 'alive', translated_text: 'живой, в живых', review_date: '2017-05-24')
Card.create(original_text: 'crowd', translated_text: 'толпа, давить, толкать', review_date: '2017-05-24')
Card.create(original_text: 'quarter', translated_text: 'четверть, четвёртая часть', review_date: '2017-05-24')
Card.create(original_text: 'written', translated_text: 'прич. прош. вр. от write', review_date: '2017-05-24')
Card.create(original_text: 'distance', translated_text: 'расстояние; дистанция', review_date: '2017-05-24')
Card.create(original_text: 'laid', translated_text: 'прош. вр., прич. прош. вр. от lay', review_date: '2017-05-24')
Card.create(original_text: 'hat', translated_text: 'шляпа, шляпка; шапка', review_date: '2017-05-24')
Card.create(original_text: 'trust', translated_text: 'вера, доверие, надежда', review_date: '2017-05-24')
Card.create(original_text: 'beauty', translated_text: 'красота', review_date: '2017-05-24')
Card.create(original_text: 'tongue', translated_text: 'язык', review_date: '2017-05-24')
Card.create(original_text: 'arrive', translated_text: 'прибывать, приезжать', review_date: '2017-05-24')
Card.create(original_text: 'center', translated_text: 'центр', review_date: '2017-05-24')
Card.create(original_text: 'drove', translated_text: 'ездил, вёз, гнал', review_date: '2017-05-24')
Card.create(original_text: 'dare', translated_text: 'осмеливаться, сметь', review_date: '2017-05-24')
Card.create(original_text: 'merry', translated_text: 'весёлый; радостный', review_date: '2017-05-24')
Card.create(original_text: 'moon', translated_text: 'луна, спутник (планеты)', review_date: '2017-05-24')
Card.create(original_text: 'circle', translated_text: 'круг, круговорот; цикл', review_date: '2017-05-24')
Card.create(original_text: 'leader', translated_text: 'руководитель, глава, лидер', review_date: '2017-05-24')
Card.create(original_text: 'conversation', translated_text: 'разговор, беседа', review_date: '2017-05-24')
Card.create(original_text: 'expression', translated_text: 'выражение', review_date: '2017-05-24')
Card.create(original_text: 'guard', translated_text: 'охрана, защита', review_date: '2017-05-24')
Card.create(original_text: 'truck', translated_text: 'грузовик, обмен, обменивать', review_date: '2017-05-24')
Card.create(original_text: 'effort', translated_text: 'усилие, попытка; напряжение', review_date: '2017-05-24')
Card.create(original_text: 'fight', translated_text: 'драться, сражаться, бой, борьба', review_date: '2017-05-24')
Card.create(original_text: 'reading', translated_text: 'чтение', review_date: '2017-05-24')
Card.create(original_text: 'group', translated_text: 'группа; группировка, фракция', review_date: '2017-05-24')
Card.create(original_text: 'mention', translated_text: 'упоминание; ссылка', review_date: '2017-05-24')
Card.create(original_text: 'forth', translated_text: 'вперёд, дальше, впредь', review_date: '2017-05-24')
Card.create(original_text: 'haven', translated_text: 'гавань, порт, убежище, укрытие', review_date: '2017-05-24')
Card.create(original_text: 'strength', translated_text: 'сила', review_date: '2017-05-24')
Card.create(original_text: 'gate', translated_text: 'ворота; дверь, калитка', review_date: '2017-05-24')
Card.create(original_text: 'radio', translated_text: 'радио, радиовещание', review_date: '2017-05-24')
Card.create(original_text: 'sick', translated_text: 'больной, болезненный; нездоровый', review_date: '2017-05-24')
Card.create(original_text: 'mad', translated_text: 'сумасшедший, ненормальный', review_date: '2017-05-24')
Card.create(original_text: 'writing', translated_text: 'письмо, писание', review_date: '2017-05-24')
Card.create(original_text: 'library', translated_text: 'библиотека', review_date: '2017-05-24')
Card.create(original_text: 'music', translated_text: 'музыка', review_date: '2017-05-24')
Card.create(original_text: 'paid', translated_text: 'платил, заплатил', review_date: '2017-05-24')
Card.create(original_text: 'immediately', translated_text: 'прямо, непосредственно', review_date: '2017-05-24')
Card.create(original_text: 'tall', translated_text: 'высокий', review_date: '2017-05-24')
Card.create(original_text: 'action', translated_text: 'действие, поступок; акция', review_date: '2017-05-24')
Card.create(original_text: 'evil', translated_text: 'зло; вред; убыток, ущерб', review_date: '2017-05-24')
Card.create(original_text: 'wet', translated_text: 'мокрый, влажный', review_date: '2017-05-24')
Card.create(original_text: 'concern', translated_text: 'проблема; вопрос, интерес', review_date: '2017-05-24')
Card.create(original_text: 'dad', translated_text: 'папа, папочка', review_date: '2017-05-24')
Card.create(original_text: 'especially', translated_text: 'особенно, в особенности', review_date: '2017-05-24')
Card.create(original_text: 'purpose', translated_text: 'цель, намерение', review_date: '2017-05-24')
Card.create(original_text: 'enemy', translated_text: 'враг, вражеский', review_date: '2017-05-24')
Card.create(original_text: 'special', translated_text: 'особый, особенный, специальный', review_date: '2017-05-24')
Card.create(original_text: 'boss', translated_text: 'хозяин, шеф, босс', review_date: '2017-05-24')
Card.create(original_text: 'likely', translated_text: 'вероятный, возможный, вероятно', review_date: '2017-05-24')
Card.create(original_text: 'soul', translated_text: 'душа; сердце', review_date: '2017-05-24')
Card.create(original_text: 'speaking', translated_text: 'беседа, разговор, говорящий', review_date: '2017-05-24')
Card.create(original_text: 'spirit', translated_text: 'дух, привидение', review_date: '2017-05-24')
Card.create(original_text: 'boat', translated_text: 'лодка; шлюпка', review_date: '2017-05-24')
Card.create(original_text: 'cigarette', translated_text: 'сигарета; папироса', review_date: '2017-05-24')
Card.create(original_text: 'faint', translated_text: 'слабый, ослабевший; вялый', review_date: '2017-05-24')
Card.create(original_text: 'perfect', translated_text: 'совершенный, безупречный', review_date: '2017-05-24')
Card.create(original_text: 'enjoy', translated_text: 'наслаждаться', review_date: '2017-05-24')
Card.create(original_text: 'flat', translated_text: 'плоский, плоскость, квартира', review_date: '2017-05-24')
Card.create(original_text: 'blow', translated_text: 'веять, дуть, дуновение', review_date: '2017-05-24')
Card.create(original_text: 'forty', translated_text: 'сорок', review_date: '2017-05-24')
Card.create(original_text: 'simple', translated_text: 'несложный, простой, лёгкий', review_date: '2017-05-24')
Card.create(original_text: 'dozen', translated_text: 'дюжина', review_date: '2017-05-24')
Card.create(original_text: 'hello', translated_text: 'привет! алло!', review_date: '2017-05-24')
Card.create(original_text: 'self', translated_text: 'собственная личность, своё "я"', review_date: '2017-05-24')
Card.create(original_text: 'everybody', translated_text: 'каждый, всякий человек; все', review_date: '2017-05-24')
Card.create(original_text: 'flash', translated_text: 'вспышка, сверкание', review_date: '2017-05-24')
Card.create(original_text: 'gain', translated_text: 'добывать, зарабатывать', review_date: '2017-05-24')
Card.create(original_text: 'shock', translated_text: 'потрясение, удар; шок', review_date: '2017-05-24')
Card.create(original_text: 'charge', translated_text: 'заряжать', review_date: '2017-05-24')
Card.create(original_text: 'danger', translated_text: 'опасность', review_date: '2017-05-24')
Card.create(original_text: 'impossible', translated_text: 'невозможный, невыполнимый', review_date: '2017-05-24')
Card.create(original_text: 'hi', translated_text: 'здорово!, привет!', review_date: '2017-05-24')
Card.create(original_text: 'million', translated_text: 'миллион', review_date: '2017-05-24')
Card.create(original_text: 'pack', translated_text: 'пачка, упаковывать, запаковывать', review_date: '2017-05-24')
Card.create(original_text: 'thoracic', translated_text: 'грудной', review_date: '2017-05-24')
Card.create(original_text: 'knowing', translated_text: 'знание, осведомлённость', review_date: '2017-05-24')
Card.create(original_text: 'public', translated_text: 'общественный; государственный, публика', review_date: '2017-05-24')
Card.create(original_text: 'stream', translated_text: 'поток, река, ручей', review_date: '2017-05-24')
Card.create(original_text: 'han', translated_text: 'китаец; китаянка', review_date: '2017-05-24')
Card.create(original_text: 'mostly', translated_text: 'главным образом, по большей части', review_date: '2017-05-24')
Card.create(original_text: 'shoe', translated_text: 'туфля; полуботинок', review_date: '2017-05-24')
Card.create(original_text: 'eating', translated_text: 'принятие пищи; еда, едящий', review_date: '2017-05-24')
Card.create(original_text: 'flower', translated_text: 'цветок', review_date: '2017-05-24')
Card.create(original_text: 'grass', translated_text: 'трава, травинка; дёрн', review_date: '2017-05-24')
Card.create(original_text: 'history', translated_text: 'история', review_date: '2017-05-24')
Card.create(original_text: 'prove', translated_text: 'доказывать', review_date: '2017-05-24')
Card.create(original_text: 'song', translated_text: 'песня; романс', review_date: '2017-05-24')
Card.create(original_text: 'affair', translated_text: 'дело, событие, мероприятие', review_date: '2017-05-24')
Card.create(original_text: 'carefully', translated_text: 'тщательно, внимательно', review_date: '2017-05-24')
Card.create(original_text: 'natural', translated_text: 'естественный, природный, натуральный', review_date: '2017-05-24')
Card.create(original_text: 'thick', translated_text: 'толстый; полный', review_date: '2017-05-24')
Card.create(original_text: 'manage', translated_text: 'руководить, управлять', review_date: '2017-05-24')
Card.create(original_text: 'marriage', translated_text: 'брак, супружество; замужество', review_date: '2017-05-24')
Card.create(original_text: 'spent', translated_text: 'прош. вр., прич. прош. вр. от spend', review_date: '2017-05-24')
Card.create(original_text: 'art', translated_text: 'искусство', review_date: '2017-05-24')
Card.create(original_text: 'easily', translated_text: 'легко; свободно', review_date: '2017-05-24')
